### ISSUE TITLE
📖​ Rapport du stage

### ISSUE THREAD

**Issue by morgancarre** [adriens/api-forfaits-opt#12]
## ✅ Livrable attendu
- Un fichier LaTeX contenant un abstract et une introduction.

**Comment by adriens** [comment]
Yes ce sera pour la prise en main de LaTeX

**Comment by morgancarre** [comment]
[rapport_latex.zip](https://github.com/user-attachments/files/18142756/rapport_latex.zip)

J'ai fait une première version du début du rapport (page de garde et abstract) en latex .

Sinon voila le pdf : 
[rapport_de_stage_v2.pdf](https://github.com/user-attachments/files/18142758/rapport_de_stage_v2.pdf)

**Comment by adriens** [comment]
Mettre les sources du rapport sur la repo genre dans rapport stp
C du  code
