### ISSUE TITLE
🚀 Initialiser le projet Quarkus

### ISSUE THREAD

**Issue by morgancarre** [adriens/api-forfaits-opt#5]
# 🎯​ Goal
Initialiser un projet Quarkus sans données.

# 📝 Tâches
- [x] Initialiser un projet Quarkus via Maven :
  ```bash 
  mvn io.quarkus:quarkus-maven-plugin:create
- [x] Endpoint type "Hello World"

**Comment by morgancarre** [comment]
@adriens avec quelle version java il faudrait que j'initialise le projet ?

**Comment by adriens** [comment]
> @adriens avec quelle version java il faudrait que j'initialise le projet ?

La 23 si tu peux. Utrilise sdkman pour installer maven, quarkus, java,...: https://dev.to/optnc/sdkman-for-dummies-38m1

**Comment by morgancarre** [comment]
yes je l'utilise, c'est bien pratique :+1:

**Comment by adriens** [comment]
Ça fera partie de ton rapport 
Note dans une issue dédiée chaque élément de la stack au fur et a mesure

**Comment by adriens** [comment]
Tu démarres bien le projet et la collaboration est top.... continue c good
