### ISSUE TITLE
🛠 Configurer Flyway

### ISSUE THREAD

**Issue by morgancarre** [adriens/api-forfaits-opt#6]
# 🎯​ Goal
Comprendre **Flyway** et l'intégrer au projet **Quarkus**.

## 📝 Tâches
- [x] Lire la documentation de [Flyway](https://quarkus.io/guides/flyway) et comprendre son intégration dans Quarkus.
- [x] Ajouter **Flyway** au projet.

**Comment by adriens** [comment]
:ok_man: Idéal pour démarrer sur les catégories de forfaits qui seront implémentés via une table simple mais avec une PK
