### ISSUE TITLE
🌐  Ajouter un endpoint `/offres`

### ISSUE THREAD

**Issue by morgancarre** [adriens/api-forfaits-opt#7]
# 🎯 Goal
Création d'un endpoint `/offres` qui renvoie les gammes de forfaits, avec les données gérées par Flyway.

## 📝 Tâches
- [x] Créer le fichier de migration SQL pour mettre en place les données des forfaits.
- [x]  Ajouter la logique dans Quarkus pour récupérer les données de la base de données via `/offres`.
- [x] Screenshot d'un appel avec `httpie`.

**Comment by adriens** [comment]
yes, bonne segmentation des tâches @morgancarre 👍

**Comment by morgancarre** [comment]
![Capture d’écran du 2024-12-20 14-18-48](https://github.com/user-attachments/assets/e00b4e82-f871-4f12-8650-fab664ef2d36)

**Comment by adriens** [comment]
yes :clap: et voila ! ta première API prend forme @morgancarre  :clap:

**Comment by morgancarre** [comment]
Salut @adriens,
En travaillant sur mon rapport, je me suis rendu compte que j'avais oublié de te signaler un point : j'ai dû passer en Java 21, car Hibernate ORM n'était pas compatible avec Java 23. En utilisant la version 21.0.2-open, tout fonctionne correctement.

**Comment by adriens** [comment]
Très bien, joli coup :+1:
